name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-all-features
        use-tool-cache: true
    - name: Check with features
      run: cargo check-all-features
    - name: Check examples
      run: cargo check --examples