name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@install-cargo-binstall-1.0.0
    - name: Install cargo-all-features
      run: cargo binstall cargo-all-features -y
    - name: Check with features
      run: cargo check-all-features
    - name: Check examples
      run: cargo check --examples